import{a as L,i,S as v}from"./assets/vendor-DFCQGEf1.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const S=15,g=async(s,o=1)=>{try{const r=await L.get("https://pixabay.com/api/",{params:{key:"50285738-1ed6c89d653294dbf28cfa2b7",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:S}});return{hits:r.data.hits,totalHits:r.data.totalHits}}catch{i.error({message:"Failed to fetch images. Please try again later.",position:"topRight"})}},u=document.querySelector(".gallery");let q=new v(".gallery a");const m=s=>{const o=s.map(({webformatURL:r,largeImageURL:n,tags:e,likes:t,views:a,comments:b,downloads:w})=>`
    <div class="image-card">
      <a href="${n}" target="_blank">
        <img src="${r}" alt="${e}" />
      </a>
      <div class="card-info">
        <span><strong>Likes</strong><br>${t}</span>
        <span><strong>Views</strong><br>${a}</span>
        <span><strong>Comments</strong><br>${b}</span>
        <span><strong>Downloads</strong><br>${w}</span>
      </div>
    </div>
  `).join("");u.insertAdjacentHTML("beforeend",o),q.refresh()},R=()=>{u.innerHTML=""},p=document.querySelector(".loader"),f=()=>{p.style.display="flex"},h=()=>{p.style.display="none"},d=document.querySelector(".btn-load-more"),B=()=>{d.style.display="flex"},y=()=>{d.style.display="none"},O=document.querySelector(".form");let l="",c;O.addEventListener("submit",async s=>{s.preventDefault();const o=s.currentTarget.elements["search-text"].value.trim();if(!o){i.warning({message:"Please enter a search term!",position:"topRight"});return}l=o,c=1,R(),y(),f();try{const{hits:r,totalHits:n}=await g(l,c);if(r.length===0){i.info({message:"No images found for your query.",position:"topRight"});return}m(r);const e=document.querySelector(".image-card");if(e){const a=e.getBoundingClientRect().height*2;window.scrollBy({top:a,behavior:"smooth"})}document.querySelectorAll(".image-card").length<n?B():i.warning({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{i.error({message:"Failed to fetch images!",position:"topRight"})}finally{h()}});d.addEventListener("click",async()=>{f();try{c+=1;const{hits:s,totalHits:o}=await g(l,c);m(s);const r=document.querySelector(".image-card");if(r){const t=r.getBoundingClientRect().height*2;window.scrollBy({top:t,behavior:"smooth"})}document.querySelectorAll(".image-card").length>=o&&(y(),i.warning({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({message:"Failed to load more images!",position:"topRight"})}finally{h()}});
//# sourceMappingURL=index.js.map
